---
- name: install WANDisco yum repository to install latest version of git for CentOS
  yum:
    name: http://opensource.wandisco.com/centos/{{ ansible_distribution_major_version }}/git/x86_64/wandisco-git-release-{{ ansible_distribution_major_version }}-1.noarch.rpm
  when: ansible_distribution == 'CentOS'

- name: install git
  yum:
    name: git
